apiVersion: v1
kind: Pod
metadata: 
  name: busybox2
  namespaces: devel
  labels: 
    app: busybox 
spec:
  containers: 
  - name: busy-pod
    image: busybox 
    command: 
    - sleep
    - "3600"
